// components
export {default as Header} from './components/header/Header'
export {default as TinderCards} from './components/tindercCard/TinderCards'
export {default as SwipeButtons} from './components/swipeButtons/SwipeButons'
export {default as Chat} from './components/chat/Chat'
// export {default as } from './components/'
// export {default as } from './components//'
// export {default as } from './components//'
// export {default as } from './components//'
// export {default as } from './components//'

// Icons
export {default as Person} from '@mui/icons-material/Person'
export {default as Forum} from '@mui/icons-material/Forum'
export {default as IButton} from '@mui/material/IconButton'
export {default as ReplayIcon} from '@mui/icons-material/Replay'
export {default as CloseIcon} from '@mui/icons-material/Close'
export {default as StarRateIcon} from '@mui/icons-material/StarRate'
export {default as FavoriteIcon} from '@mui/icons-material/Favorite'
export {default as FlashOnIcon} from '@mui/icons-material/FlashOn'
export {default as ArrowBackIcon} from '@mui/icons-material/ArrowBackIosNew'
// export {default as } from '@mui/icons-material/'

// pages
export {default as Chats} from './pages/chats/Chats'
export {default as Home} from './pages/home/Home'
export {default as ChatScreen} from './pages/chatScreen/ChatScreen'
// export {default as } from './pages//'
// export {default as } from './pages//'
// export {default as } from './pages//'
// export {default as } from './pages//'
